'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class RecursosTitulos
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UGPP.CobrosCoactivo.Logica.RecursosTitulos", GetType(RecursosTitulos).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Area origen --.
        '''</summary>
        Friend Shared ReadOnly Property areaorigen() As String
            Get
                Return ResourceManager.GetString("areaorigen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ciudad --.
        '''</summary>
        Friend Shared ReadOnly Property ciudad() As String
            Get
                Return ResourceManager.GetString("ciudad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Departamento -- .
        '''</summary>
        Friend Shared ReadOnly Property departamento() As String
            Get
                Return ResourceManager.GetString("departamento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta diligenciar datos de deudor --.
        '''</summary>
        Friend Shared ReadOnly Property deudor() As String
            Get
                Return ResourceManager.GetString("deudor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección completa --.
        '''</summary>
        Friend Shared ReadOnly Property direccioncompleta() As String
            Get
                Return ResourceManager.GetString("direccioncompleta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta diligenciar datos de direcciones--.
        '''</summary>
        Friend Shared ReadOnly Property direcciones() As String
            Get
                Return ResourceManager.GetString("direcciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta diligenciar datos de documentos--.
        '''</summary>
        Friend Shared ReadOnly Property documentos() As String
            Get
                Return ResourceManager.GetString("documentos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Señor Usuario: Falta diligenciar los siguientes campos:.
        '''</summary>
        Friend Shared ReadOnly Property errorGeneral() As String
            Get
                Return ResourceManager.GetString("errorGeneral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta documento --.
        '''</summary>
        Friend Shared ReadOnly Property faltadocumento() As String
            Get
                Return ResourceManager.GetString("faltadocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Ejecutoria --.
        '''</summary>
        Friend Shared ReadOnly Property fchejecutoria() As String
            Get
                Return ResourceManager.GetString("fchejecutoria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Ejecutoria no puede ser superior a la fecha actual --.
        '''</summary>
        Friend Shared ReadOnly Property fchejecutoriasuperior() As String
            Get
                Return ResourceManager.GetString("fchejecutoriasuperior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta diligenciar la fecha--.
        '''</summary>
        Friend Shared ReadOnly Property fchenotificacion() As String
            Get
                Return ResourceManager.GetString("fchenotificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Exigibilidad --.
        '''</summary>
        Friend Shared ReadOnly Property fchexigibilidad() As String
            Get
                Return ResourceManager.GetString("fchexigibilidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de Exigibilidad no puede ser superior a la fecha actual --.
        '''</summary>
        Friend Shared ReadOnly Property fchexigibilidadsuperior() As String
            Get
                Return ResourceManager.GetString("fchexigibilidadsuperior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de notificación no puede ser superior a la fecha actual --.
        '''</summary>
        Friend Shared ReadOnly Property fchnotificacionsuperior() As String
            Get
                Return ResourceManager.GetString("fchnotificacionsuperior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha de notificación del título ejecutivo --.
        '''</summary>
        Friend Shared ReadOnly Property fchnotificaciontituloejec() As String
            Get
                Return ResourceManager.GetString("fchnotificaciontituloejec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha del título ejecutivo --.
        '''</summary>
        Friend Shared ReadOnly Property fchtituloejecutivo() As String
            Get
                Return ResourceManager.GetString("fchtituloejecutivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fecha del título ejecutivo no puede ser superior a la fecha actual --.
        '''</summary>
        Friend Shared ReadOnly Property fchtituloejecutivosuperior() As String
            Get
                Return ResourceManager.GetString("fchtituloejecutivosuperior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Forma de Notificación --.
        '''</summary>
        Friend Shared ReadOnly Property formanotificacion() As String
            Get
                Return ResourceManager.GetString("formanotificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fuente de la dirección --.
        '''</summary>
        Friend Shared ReadOnly Property fuendireccion() As String
            Get
                Return ResourceManager.GetString("fuendireccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre del deudor --.
        '''</summary>
        Friend Shared ReadOnly Property nombredeudor() As String
            Get
                Return ResourceManager.GetString("nombredeudor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número de expediente de origen --.
        '''</summary>
        Friend Shared ReadOnly Property numeroexporigen() As String
            Get
                Return ResourceManager.GetString("numeroexporigen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número de identificación -- .
        '''</summary>
        Friend Shared ReadOnly Property numeroidentificacion() As String
            Get
                Return ResourceManager.GetString("numeroidentificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Número de título ejecutivo --.
        '''</summary>
        Friend Shared ReadOnly Property numerotituloejecutivo() As String
            Get
                Return ResourceManager.GetString("numerotituloejecutivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Otras fuente de la dirección --.
        '''</summary>
        Friend Shared ReadOnly Property otrasfuentesdireccion() As String
            Get
                Return ResourceManager.GetString("otrasfuentesdireccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Cartera --.
        '''</summary>
        Friend Shared ReadOnly Property tipocartera() As String
            Get
                Return ResourceManager.GetString("tipocartera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo  de identificación --.
        '''</summary>
        Friend Shared ReadOnly Property tipoidentificacion() As String
            Get
                Return ResourceManager.GetString("tipoidentificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Obligación --.
        '''</summary>
        Friend Shared ReadOnly Property tipoobligacion() As String
            Get
                Return ResourceManager.GetString("tipoobligacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo Persona -- .
        '''</summary>
        Friend Shared ReadOnly Property tipopersona() As String
            Get
                Return ResourceManager.GetString("tipopersona", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Falta diligenciar datos de título ejecutivo--.
        '''</summary>
        Friend Shared ReadOnly Property tituloejecutivo() As String
            Get
                Return ResourceManager.GetString("tituloejecutivo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to cod guid --.
        '''</summary>
        Friend Shared ReadOnly Property codguid() As String
            Get
                Return ResourceManager.GetString("codguid", resourceCulture)
            End Get
        End Property
        '''<summary>
        '''  Looks up a localized string similar to codTipo Documento --.
        '''</summary>
        Friend Shared ReadOnly Property codTipoDocumento() As String
            Get
                Return ResourceManager.GetString("codTipoDocumento", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to valores Obligatorios --.
        '''</summary>
        Friend Shared ReadOnly Property valoresObligatorios() As String
            Get
                Return ResourceManager.GetString("valoresObligatorios", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Total Obligación del título --.
        '''</summary>
        Friend Shared ReadOnly Property totalobligaciontitulo() As String
            Get
                Return ResourceManager.GetString("totalobligaciontitulo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to desruta Doc --.
        '''</summary>
        Friend Shared ReadOnly Property desrutaDoc() As String
            Get
                Return ResourceManager.GetString("desrutaDoc", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Valor del título ejecutivo --.
        '''</summary>
        Friend Shared ReadOnly Property valortituloejecutivo() As String
            Get
                Return ResourceManager.GetString("valortituloejecutivo", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
