IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[SP_InsertaDocumento]')
                    AND type IN ( N'P', N'PC' ) ) 

BEGIN 
	DROP PROCEDURE [dbo].[SP_InsertaDocumento]  
END


GO



-- =============================================
-- Author: CARLOS FELIPE MOTTA MONJE	
-- Create date: 31/10/2018
-- Description: INSERTA EL DOCUMENTO
-- =============================================

CREATE PROCEDURE [dbo].[SP_InsertaDocumento] 

       @ID_DOCUMENTO_TITULO INT,
       @ID_MAESTRO_TITULO BIGINT,
       @DES_RUTA_DOCUMENTO VARCHAR(200),
       @TIPO_RUTA  INT,
       @COD_GUID VARCHAR(50)=NULL,
       @COD_TIPO_DOCUMENTO_AO VARCHAR(50)=null,
       @NOM_DOC_AO VARCHAR(50)=NULL,
       @OBSERVA_LEGIBILIDAD VARCHAR(50)=NULL,
       @NUM_PAGINAS INT=NULL


   AS
   
BEGIN                     
    
SET NOCOUNT ON   

		IF EXISTS (SELECT * FROM [dbo].[MAESTRO_TITULOS_DOCUMENTOS] WHERE  ID_DOCUMENTO_TITULO =  @ID_DOCUMENTO_TITULO AND ID_MAESTRO_TITULO = @ID_MAESTRO_TITULO)

		BEGIN

		UPDATE  [dbo].[MAESTRO_TITULOS_DOCUMENTOS] 
		SET 
	        [ID_DOCUMENTO_TITULO] = @ID_DOCUMENTO_TITULO
           ,[ID_MAESTRO_TITULO] = @ID_MAESTRO_TITULO
           ,[DES_RUTA_DOCUMENTO] = @DES_RUTA_DOCUMENTO
           ,[TIPO_RUTA] = @TIPO_RUTA
           ,[COD_GUID] = ISNULL(@COD_GUID,[COD_GUID])
           ,[COD_TIPO_DOCUMENTO_AO] = ISNULL(@COD_TIPO_DOCUMENTO_AO,[COD_TIPO_DOCUMENTO_AO])
           ,[NOM_DOC_AO] = ISNULL(@NOM_DOC_AO,[NOM_DOC_AO])
           ,[OBSERVA_LEGIBILIDAD] = ISNULL(@OBSERVA_LEGIBILIDAD,[OBSERVA_LEGIBILIDAD])
           ,[NUM_PAGINAS] = ISNULL(@NUM_PAGINAS,[NUM_PAGINAS])

	 WHERE  ID_DOCUMENTO_TITULO =  @ID_DOCUMENTO_TITULO AND ID_MAESTRO_TITULO = @ID_MAESTRO_TITULO


		END

		ELSE
		

		BEGIN



INSERT INTO [dbo].[MAESTRO_TITULOS_DOCUMENTOS]
           ([ID_DOCUMENTO_TITULO]
           ,[ID_MAESTRO_TITULO]
           ,[DES_RUTA_DOCUMENTO]
           ,[TIPO_RUTA]
           ,[COD_GUID]
           ,[COD_TIPO_DOCUMENTO_AO]
           ,[NOM_DOC_AO]
           ,[OBSERVA_LEGIBILIDAD]
           ,[NUM_PAGINAS])
     VALUES
(@ID_DOCUMENTO_TITULO,@ID_MAESTRO_TITULO,@DES_RUTA_DOCUMENTO,@TIPO_RUTA,@COD_GUID,@COD_TIPO_DOCUMENTO_AO,@NOM_DOC_AO,@OBSERVA_LEGIBILIDAD,@NUM_PAGINAS)

 END


 END
