
/* Agregar campos */

ALTER TABLE [dbo].[DIRECCIONES]
ADD ID_FUENTE BIGINT NULL

/* Migrar datos */
UPDATE MAESTRO_TITULOS SET MT_for_notificacion_titulo = '00' WHERE MT_for_notificacion_titulo IS NULL
UPDATE MAESTRO_TITULOS SET MT_for_not_reso_resu_reposicion = '00' WHERE MT_for_not_reso_resu_reposicion IS NULL
UPDATE MAESTRO_TITULOS SET MT_for_not_reso_apela_recon = '00' WHERE MT_for_not_reso_apela_recon IS NULL
INSERT INTO [dbo].[MAESTRO_TITULOS_FOR_NOTIFICACION] ([COD_TIPO_NOTIFICACION],[FEC_NOTIFICACION],[COD_FOR_NOT],[ID_UNICO_MAESTRO_TITULOS])
SELECT 1 AS [COD_TIPO_NOTIFICACION],MT_fec_notificacion_titulo AS [FEC_NOTIFICACION],MT_for_notificacion_titulo AS [COD_FOR_NOT],idunico AS [ID_UNICO_MAESTRO_TITULOS] FROM MAESTRO_TITULOS 
UNION ALL
SELECT 2 AS [COD_TIPO_NOTIFICACION],MT_fec_not_reso_resu_reposicion AS [FEC_NOTIFICACION], MT_for_not_reso_resu_reposicion AS [COD_FOR_NOT],idunico AS [ID_UNICO_MAESTRO_TITULOS] FROM MAESTRO_TITULOS 
UNION ALL
SELECT 3 AS [COD_TIPO_NOTIFICACION],MT_fec_not_reso_apela_recon AS [FEC_NOTIFICACION], MT_for_not_reso_apela_recon AS [COD_FOR_NOT],idunico AS [ID_UNICO_MAESTRO_TITULOS] FROM MAESTRO_TITULOS

/* Eliminar campos */
IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MAESTRO_TITULOS] DROP CONSTRAINT [FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION2]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MAESTRO_TITULOS] DROP CONSTRAINT FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION2
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION1]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MAESTRO_TITULOS] DROP CONSTRAINT FK_MAESTRO_TITULOS_FORMAS_NOTIFICACION1
GO


ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_fec_notificacion_titulo;

ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_fec_not_reso_resu_reposicion;

ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_fec_not_reso_apela_recon;

ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_for_not_reso_apela_recon;

ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_for_notificacion_titulo;

ALTER TABLE MAESTRO_TITULOS
DROP COLUMN MT_for_not_reso_resu_reposicion;


--ALTER TABLE TIPOS_TITULO
--DROP COLUMN COD_PROCEDENCIA;

ALTER TABLE [dbo].TIPOS_TITULO
ADD COD_PROCEDENCIA INT

ALTER TABLE [dbo].TIPOS_TITULO ADD CONSTRAINT [FK_PROCEDENCIA_TITULOS_CODIGO] 
FOREIGN KEY (COD_PROCEDENCIA) REFERENCES [dbo].[procedencia_titulos] (CODIGO) 


UPDATE PROCEDENCIA_TITULOS SET NOMBRE='Subdirección de Determinación Parafiscales' WHERE CODIGO = 2
UPDATE PROCEDENCIA_TITULOS SET NOMBRE='Subdirección de Nomina' WHERE CODIGO = 3
UPDATE PROCEDENCIA_TITULOS SET NOMBRE='Subidrección Juridica Pensional' WHERE CODIGO = 4

INSERT INTO PROCEDENCIA_TITULOS (NOMBRE) VALUES ('Control Interno Disciplinario'),('Administrativa')

UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=3  WHERE codigo='16'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=3  WHERE codigo='03'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='01'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='08'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=4  WHERE codigo='12'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=4  WHERE codigo='15'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='17'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=6  WHERE codigo='18'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='04'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='05'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=5  WHERE codigo='10'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=2  WHERE codigo='07'
UPDATE TIPOS_TITULO SET COD_PROCEDENCIA=4  WHERE codigo='06'


ALTER TABLE [dbo].[ENTES_DEUDORES]
ADD VAL_NO_MATRICULA_MERCANTIL VARCHAR(60) NULL

ALTER TABLE [dbo].[DEUDORES_EXPEDIENTES] 
ADD ID_MAESTRO_TITULOS BIGINT NULL

ALTER TABLE [dbo].[TIPOS_TITULO] 
ADD DIAS_FECHA_PRESCRIPCION INT NULL

UPDATE [dbo].[TIPOS_TITULO] SET ANOS_FECHA_PRESCRIPCION=3 WHERE codigo='03'
UPDATE [dbo].[TIPOS_TITULO] SET ANOS_FECHA_PRESCRIPCION=5 WHERE codigo<>'03'