/****** Object:  Table [dbo].[PERFIL_MODULO]    Script Date: 07/11/2018 15:53:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERFIL_MODULO](
	[fk_perfil_id] [bigint] NOT NULL,
	[fk_modulo_id] [int] NOT NULL,
	[ind_estado] [bit] NOT NULL
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[PERFIL_MODULO]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_MODULO_MODULO_FK_MODULO_ID] FOREIGN KEY([fk_modulo_id])
REFERENCES [dbo].[MODULO] ([pk_codigo])
GO
ALTER TABLE [dbo].[PERFIL_MODULO] CHECK CONSTRAINT [FK_PERFIL_MODULO_MODULO_FK_MODULO_ID]
GO
ALTER TABLE [dbo].[PERFIL_MODULO]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_MODULOS_PERFILES_FK_PERFIL_ID] FOREIGN KEY([fk_perfil_id])
REFERENCES [dbo].[PERFILES] ([codigo])
GO
ALTER TABLE [dbo].[PERFIL_MODULO] CHECK CONSTRAINT [FK_PERFIL_MODULOS_PERFILES_FK_PERFIL_ID]
GO