

CREATE TABLE [dbo].[RELACION_ESTADO_ETAPA](
	[codigo_estado] [varchar](50) NOT NULL,
	[codigo_etapa] [int] NOT NULL,
 CONSTRAINT [PK_RELACION_ESTADO_ETAPA] PRIMARY KEY CLUSTERED 
(
	[codigo_estado] ASC,
	[codigo_etapa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


