/****** Object:  Table [dbo].[PERFIL_PAGINA]    Script Date: 07/11/2018 15:53:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERFIL_PAGINA](
	[fk_perfil_id] [bigint] NOT NULL,
	[fk_pagina_id] [int] NOT NULL,
	[ind_puede_ver] [bit] NOT NULL,
	[ind_puede_editar] [bit] NOT NULL,
	[ind_estado] [bit] NOT NULL
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[PERFIL_PAGINA]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_PAGINA_PERFILES_FK_PAGINA_ID] FOREIGN KEY([fk_pagina_id])
REFERENCES [dbo].[PAGINA] ([pk_codigo])
GO
ALTER TABLE [dbo].[PERFIL_PAGINA] CHECK CONSTRAINT [FK_PERFIL_PAGINA_PERFILES_FK_PAGINA_ID]
GO
ALTER TABLE [dbo].[PERFIL_PAGINA]  WITH CHECK ADD  CONSTRAINT [FK_PERFIL_PAGINA_PERFILES_FK_PERFIL_ID] FOREIGN KEY([fk_perfil_id])
REFERENCES [dbo].[PERFILES] ([codigo])
GO
ALTER TABLE [dbo].[PERFIL_PAGINA] CHECK CONSTRAINT [FK_PERFIL_PAGINA_PERFILES_FK_PERFIL_ID]
GO