'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ALMACENAMIENTO_TEMPORAL
    Public Property ID_ALMACENAMIENTO_TEMPORAL As Long
    Public Property JSON_OBJ As String
    Public Property ID_TAREA_ASIGNADA As Nullable(Of Long)
    Public Property FEC_ACTUALIZACION As Date

    Public Overridable Property TAREA_ASIGNADA As TAREA_ASIGNADA

End Class
