'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OBSERVACIONESDOC_CUMPLE_NOCUMPLE
    Public Property ID_OBSERVACIONESDOC As Long
    Public Property ID_UNICO_MT As Long
    Public Property ID_DOCUMENTO As Long
    Public Property USUARIO As String
    Public Property DESTINATARIO As String
    Public Property FCHENVIO As Date
    Public Property OBSERVACIONES As String
    Public Property CUMPLE_NOCUMPLE As Boolean

End Class
