'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PERFIL_MODULO
    Public Property fk_perfil_id As Long
    Public Property fk_modulo_id As Integer
    Public Property ind_estado As Boolean

    Public Overridable Property PERFILES As PERFILES
    Public Overridable Property MODULO As MODULO

End Class
