'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TAREA_SOLICITUD
    Public Property ID_TAREA_SOLICITUD As Long
    Public Property ID_TAREA_ASIGNADA As Long
    Public Property VAL_USUARIO_SOLICITANTE As String
    Public Property VAL_USUARIO_APROBADOR As String
    Public Property VAL_USUARIO_DESTINO As String
    Public Property VAL_TIPO_SOLICITUD As Integer
    Public Property COD_SOLICITUD_CAMBIO_ESTADO As Nullable(Of Long)
    Public Property VAL_TIPOLOGIA As String
    Public Property ID_TAREA_OBSERVACION As Nullable(Of Integer)
    Public Property IND_SOLICITUD_PROCESADA As Boolean
    Public Property COD_ESTADO_SOLICITUD As Nullable(Of Integer)
    Public Property FEC_SOLICITUD As Nullable(Of Date)

    Public Overridable Property SOLICITUDES_CAMBIOESTADO As SOLICITUDES_CAMBIOESTADO
    Public Overridable Property SOLICITUDES_CAMBIOESTADO1 As SOLICITUDES_CAMBIOESTADO
    Public Overridable Property TAREA_ASIGNADA As TAREA_ASIGNADA
    Public Overridable Property TAREA_OBSERVACION As TAREA_OBSERVACION

End Class
