'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TAREA_OBSERVACION
    Public Property COD_ID_TAREA_OBSERVACION As Integer
    Public Property OBSERVACION As String
    Public Property IND_ESTADO As Boolean
    Public Property FEC_CREACION As Date

    Public Overridable Property TAREA_ASIGNADA As ICollection(Of TAREA_ASIGNADA) = New HashSet(Of TAREA_ASIGNADA)
    Public Overridable Property TAREA_SOLICITUD As ICollection(Of TAREA_SOLICITUD) = New HashSet(Of TAREA_SOLICITUD)

End Class
