'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPOS_APORTANTES
    Public Property codigo As String
    Public Property nombre As String
    Public Property ind_estado As Nullable(Of Boolean)

    Public Overridable Property ENTES_DEUDORES As ICollection(Of ENTES_DEUDORES) = New HashSet(Of ENTES_DEUDORES)

End Class
