'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_DOCUMENTAL
    Public Property Id_Tipo_Documental As Integer
    Public Property Codigo As String
    Public Property Nombre As String
    Public Property Id_Serie As Integer
    Public Property Id_Subserie As Nullable(Of Integer)

    Public Overridable Property DOCUMENTO_TITULO As ICollection(Of DOCUMENTO_TITULO) = New HashSet(Of DOCUMENTO_TITULO)
    Public Overridable Property SERIE As SERIE
    Public Overridable Property SUBSERIE As SUBSERIE

End Class
