'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPOS_TITULO
    Public Property codigo As String
    Public Property nombre As String
    Public Property ID_TIPO_CARTERA As Nullable(Of Integer)
    Public Property COD_PROCEDENCIA As Nullable(Of Integer)
    Public Property DIAS_MAX_GESTION_AMARILLO As Nullable(Of Integer)
    Public Property DIAS_MAX_GESTION_ROJO As Nullable(Of Integer)
    Public Property ANOS_FECHA_PRESCRIPCION As Nullable(Of Integer)

    Public Overridable Property MAESTRO_TITULOS As ICollection(Of MAESTRO_TITULOS) = New HashSet(Of MAESTRO_TITULOS)

End Class
