'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPOS_PROCESOS_CONCURSALES
    Public Property codigo As Integer
    Public Property nombre As String
    Public Property PROCESO_JURIDICO As Nullable(Of Integer)
    Public Property PROCESO_NATURAL As Nullable(Of Integer)
    Public Property ESTADO_PROCESO_J As String
    Public Property ESTADO_PROCESO_N As String

End Class
