IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[SP_GrillaAreaOrigen]')
                    AND type IN ( N'P', N'PC' ) ) 

BEGIN 
	DROP PROCEDURE [dbo].[SP_GrillaAreaOrigen]
END


GO

-- =============================================
-- Author: CARLOS FELIPE MOTTA MONJE	
-- Create date: 13/11/2018
-- Description: CARGA LOS DATOS PARA LA GRILLA DE LA BANDEJA DE TITULOS AREA ORIGEN
--- EXEC [SP_GrillaAreaOrigen] 'MFONG','',0,0,'','','',''
--  EXEC [SP_GrillaAreaOrigen] 'MFONG','',0,0,'18/11/2018','','',''
-- =============================================

CREATE PROCEDURE [dbo].[SP_GrillaAreaOrigen] 

   @USULOG AS VARCHAR(20), -- Usuario al cual se le asigno la tarea
   @NROTITULO AS VARCHAR(50) , -- Número de título
   @ESTADOPROCESAL AS INT,
   @ESTADOSOPERATIVO AS INT,
   @FCHENVIOCOBRANZADESDE AS VARCHAR(10),
   @FCHENVIOCOBRANZAHASTA AS VARCHAR(10),
   @NROIDENTIFICACIONDEUDOR AS VARCHAR(50),
   @NOMBREDEUDOR AS VARCHAR (50)
   AS
   
BEGIN                     
      
SET NOCOUNT ON 

DECLARE @NUMERODIAS INT 
SELECT @NUMERODIAS = VAL_VALOR FROM DOMINIO_DETALLE WHERE ID_DOMINIO_DETALLE =11
		   SELECT 
		   TA.ID_UNICO_TITULO AS IDUNICO,
		   TA.ID_TAREA_ASIGNADA,
		   MT.MT_nro_titulo AS NROTITULO,
			CONVERT(VARCHAR(10),MT.MT_fec_expedicion_titulo,103) AS FCHEXPEDICIONTITULO,
		   ED.ED_Nombre AS NOMBREDEUDOR,
		   ED.ED_Codigo_Nit AS NRONITCEDULA,
		   TT.nombre AS TIPOOBLIGACION,
		   MT.totaldeuda AS TOTALOBLIGACION,
		   CONVERT(VARCHAR(10),TA.FEC_ENTREGA_GESTOR,103) AS FEC_ENTREGA_GESTOR, 
		   CONVERT(VARCHAR(10),FEC_ENTREGA_GESTOR +  @NUMERODIAS ,103)  AS FCHLIMITE, 
		   CASE WHEN   CONVERT(VARCHAR(10),FEC_ENTREGA_GESTOR +  @NUMERODIAS ,103) < = CONVERT(VARCHAR(10),GETDATE()  ,103)THEN 'ROJO' 
		        END
		    AS COLOR,
		   EO.ID_ESTADO_OPERATIVOS,
		   AT.JSON_OBJ AS JSON_ALMACENAMIENTO
		   FROM TAREA_ASIGNADA TA
			LEFT JOIN [dbo].[ESTADO_OPERATIVO] EO WITH (NOLOCK) ON TA.COD_ESTADO_OPERATIVO = EO.ID_ESTADO_OPERATIVOS
			LEFT JOIN MAESTRO_TITULOS MT WITH (NOLOCK) ON MT.idunico = TA.ID_UNICO_TITULO
			LEFT JOIN [dbo].[TIPOS_TITULO] TT WITH (NOLOCK) ON TT.codigo = MT.MT_tipo_titulo
			LEFT JOIN [dbo].[DEUDORES_EXPEDIENTES] DE WITH (NOLOCK) ON MT.idunico = DE.ID_MAESTRO_TITULOS
			LEFT JOIN [dbo].[ENTES_DEUDORES] ED WITH (NOLOCK) ON DE.deudor = ED.ED_Codigo_Nit
			LEFT JOIN [dbo].[ALMACENAMIENTO_TEMPORAL] AT WITH (NOLOCK) ON AT.ID_TAREA_ASIGNADA = TA.ID_TAREA_ASIGNADA
			LEFT JOIN [dbo].[EJEFISGLOBAL] EJEF WITH (NOLOCK) ON EJEF.EFINROEXP = MT.MT_expediente
		
			WHERE 

			((@USULOG IS NULL) OR (VAL_USUARIO_NOMBRE = @USULOG)) AND
			((@NROTITULO = '') OR (UPPER(MT_nro_titulo) LIKE '%' + UPPER(@NROTITULO) + '%')) AND
			((@ESTADOSOPERATIVO = 0) OR (EO.ID_ESTADO_OPERATIVOS = @ESTADOSOPERATIVO)) AND
			((@FCHENVIOCOBRANZADESDE = '') OR (CONVERT(VARCHAR(10),TA.FEC_ENTREGA_GESTOR,103) >= @FCHENVIOCOBRANZADESDE)) AND
			((@FCHENVIOCOBRANZAHASTA = '') OR (CONVERT(VARCHAR(10),TA.FEC_ENTREGA_GESTOR,103) <= @FCHENVIOCOBRANZAHASTA)) AND
			((@NROIDENTIFICACIONDEUDOR = '') OR (ED.ED_Codigo_Nit LIKE '%' + @NROIDENTIFICACIONDEUDOR+ '%')) AND
			((@NOMBREDEUDOR = '') OR (UPPER(ED.ED_Nombre) LIKE '%' + UPPER(@NOMBREDEUDOR) + '%')) AND
			 EO.VAL_NOMBRE IN ('EnCreacion','Subsanar')
			 ORDER BY TA.FEC_ENTREGA_GESTOR DESC
 END


