-- DX: 287976
IF EXISTS	(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'DETALLE_EMBARGO')
BEGIN	
	IF NOT EXISTS(SELECT 1	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DETALLE_EMBARGO' AND COLUMN_NAME = 'Observaciones')
		BEGIN
			ALTER TABLE DETALLE_EMBARGO 
			ADD Observaciones TEXT 
		END			
END

-- =============================================
-- Author:		Sergio J. Caceres C. 
-- Create date: 2019-02-08
-- Description:	Script para adicionar los nuevos items a la lista de Causales mostrada en "Medidas Cautelares" -> "Datos"
-- =============================================
IF NOT EXISTS (SELECT CODIGO FROM [dbo].[Causales_efectividad_embargo] WHERE CODIGO='14')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO] ([codigo],[nombre],[efectivo])
		VALUES
           ('14','NO TIENE CUENTA EN EL BANCO','NO')
		PRINT 'EL CODIGO 14 FUE INSERTADO'
	END
ELSE
	PRINT 'EL CODIGO 14 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[Causales_efectividad_embargo] WHERE CODIGO='15')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('15','CUENTA INEMBARGABLE','NO')
		PRINT 'EL CODIGO 15 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 15 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[Causales_efectividad_embargo] WHERE CODIGO='16')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           (16,'SALDO INEMBARGABLE','NO')
		PRINT 'EL CODIGO 16 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 16 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[Causales_efectividad_embargo] WHERE CODIGO='17')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('17','NO TIENE ACCIONES','NO')
		PRINT 'EL CODIGO 17 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 17 YA EXISTE'
	
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[Causales_efectividad_embargo] WHERE CODIGO='18')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
           ('18','MATRÍCULA CANCELADA','NO')
	PRINT 'EL CODIGO 18 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 18 YA EXISTE'
	
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='19')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('19','FOLIO CERRADO','NO')
		PRINT 'EL CODIGO 19 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 19 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='20')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
           ('20','TURNO RESTITUIDO','NO')
	PRINT 'EL CODIGO 20 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 20 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='21')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('21','REGISTRA EMBARGOS PREVIOS ','NO')
		PRINT 'EL CODIGO 21 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 21 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='22')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('22','FALTA COPIA AUTENTICA','NO')
		PRINT 'EL CODIGO 22 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 22 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='23')
	BEGIN	
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('23','FALTA EL PAGO DE DERECHOS PARA REGISTRO','NO')
		PRINT 'EL CODIGO 23 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 23 YA EXISTE'	

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='24')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('24','FALTA DE COMPETENCIA','NO')
		PRINT 'EL CODIGO 24 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 24 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='25')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('25','OFICIO CONTIENE ERROR EN DATOS','NO')
		PRINT 'EL CODIGO 25 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 25 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='26')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
			('26','EL DEUDOR INFORMADO NO ES PROPIETARIO DEL BIEN','NO')
		PRINT 'EL CODIGO 26 FUE INSERTADO'
		END
	ELSE
		PRINT 'EL CODIGO 26 YA EXISTE'
    
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='27')
	BEGIN       
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('27','INEMBARGABLE - AFECTACIÓN VIVIENDA FAMILIAR','NO')
		PRINT 'EL CODIGO 27 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 27 YA EXISTE'
	
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='28')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('28','INEMBARGABLE - PATRIMONIO DE FAMILIA','NO')
		PRINT 'EL CODIGO 28 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 28 YA EXISTE'		

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='29')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('29','INEMBARGABLE - LOTE DE CEMENTERIO','NO')
		PRINT 'EL CODIGO 29 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 29 YA EXISTE'
	
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='30')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
           ('30','INEMBARGABLE - OTRA CAUSAL','NO')		
		PRINT 'EL CODIGO 30 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 30 YA EXISTE'


	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='31')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('31','REQUIERE REITERACIÓN AL COMPETENTE','NO')
		PRINT 'EL CODIGO 31 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 31 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='32')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
		--Se recorta nombre esta MEDIDA_EFECTIVIDAD_EMBARGO por sugerencia de Francisco J. Sanchez S. para poder insertar en tabla. 
           /*('32','REQUIERE INFORMACIÓN ADICIONAL PARA REGISTRAR MEDIDA','NO')*/('32','REQUIERE INFORMACIÓN ADICIONAL REGISTRAR MEDIDA','NO')
		PRINT 'EL CODIGO 32 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 32 YA EXISTE'

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='33')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
		VALUES
           ('33','REGISTRO SUSPENDIDO','NO')
		PRINT 'EL CODIGO 33 FUE INSERTADO'
	END
	ELSE
		PRINT 'EL CODIGO 33 YA EXISTE'
	---------------------------------------------------
	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='34')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
           ('34','CONFIRMA REGISTRO CON EMBARGOS PREVIOS ','SI')
	PRINT 'EL CODIGO 34 FUE INSERTADO'
		END
	ELSE
		PRINT 'EL CODIGO 34 YA EXISTE'	

	IF NOT EXISTS (SELECT CODIGO FROM [dbo].[causales_efectividad_embargo] WHERE CODIGO='35')
	BEGIN
		INSERT INTO [dbo].[CAUSALES_EFECTIVIDAD_EMBARGO]
           ([codigo],[nombre],[efectivo])
     VALUES
           ('35','CONFIRMA REGISTRO SIN NOVEDADES','SI')
		END
	ELSE
		PRINT 'EL CODIGO 34 YA EXISTE'



-- DX: 269581 Bancos
-- =============================================
-- Author:		Sergio Jose Caceres Cifuentes
-- Create date: 2019-02-12
-- Caso Dexon: 269581
-- Description:	Script que actualiza la tabla [MAESTRO_BANCOS] con los dato suministrados para el caso Dexon: 269581. 
-- Sí el registro en esta tabla existe se actualiza el [BAN_NOMBRE] por el nuevo nombre; en caso contrario Sí el registro no existe en la tabla aquì mencionada se adicionará con los datos [BAN_CODIGO], '[BAN_NOMBRE]' y [BAN_DIRECCION].

-- =============================================
/*01) Actualizacion del BANCO DE LA REPUBLICA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='00')
	BEGIN
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO DE LA REPUBLICA DE COLOMBIA', 
			BAN_DIRECCION=UPPER('Carrera 7 # 14-78 Bogotá, D.C.')
			WHERE BAN_CODIGO='00'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 00 POR: BANCO DE LA REPUBLICA DE COLOMBIA' 
	END

/*02) Actualizacion del BANCO AGRARIO DE COLOMBIA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='40')
BEGIN 
	UPDATE MAESTRO_BANCOS  
	SET BAN_NOMBRE='BANCO AGRARIO DE COLOMBIA S.A.', 
	BAN_DIRECCION=UPPER('Carrera 8 No. 15-43 Bogotá D.C.')	 
	WHERE BAN_CODIGO='40'
	PRINT 'SE ACTUALIZO DATOS DEL BANCO CON CODIGO 40 POR: BANCO AGRARIO DE COLOMBIA S.A.' 
END
/*03) Actualizacion del Banco Caja Social*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='15')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO CAJA SOCIAL S.A.', 
			BAN_DIRECCION=UPPER('Carrera 7 No. 77-65 Torre Colmena Bogotá D.C.') 
		WHERE BAN_CODIGO='15'
	PRINT 'SE ACTUALIZO DATOS DEL BANCO CON CODIGO 15 POR: BANCO CAJA SOCIAL S.A.'
END
/*03) Actualizacion del Banco Caja Social*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='32')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO CAJA SOCIAL (No usar)'			 
		WHERE BAN_CODIGO='32'
	PRINT 'SE ACTUALIZO DATOS DEL BANCO CON CODIGO 32 POR: BANCO CAJA SOCIAL (No usar)'
END


/*04) Actualizacion del BANCO AV VILLAS*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='52')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO AV VILLAS', 
			BAN_DIRECCION=UPPER('Carrera 13 No. 27-47 Bogotá D.C.') 
		WHERE BAN_CODIGO='52'
  PRINT 'SE ACTUALIZO DATOS DEL BANCO CON CODIGO 52 POR: BANCO AV VILLAS' 
END

/*05) Actualizacion del BANCO CAJA SOCIAL*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='19')
BEGIN 
	UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO COLPATRIA MULTIBANCA COLPATRIA S.A. Y/O SCOTIABANK COLPATRIA S.A', 
			BAN_DIRECCION=UPPER('CL 12B # 7-90 PI 1 Bogotá D.C.') 
	WHERE BAN_CODIGO='19'
	PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 19 POR: BANCO COLPATRIA MULTIBANCA COLPATRIA S.A. Y/O SCOTIABANK COLPATRIA S.A' 
  END

/*06) Actualizacion del BANCO CAJA SOCIAL*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='61')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('61',UPPER('BANCO COMPARTIR S.A.'),UPPER('Calle 16 No. 6-66 Piso 4 Edificio Avianca Bogotá D.C.')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 61: BANCO COMPARTIR S.A.'
END
/*07) Atualizacion de BANCOOMEVA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='21')
BEGIN 
	UPDATE MAESTRO_BANCOS  
	SET BAN_NOMBRE='BANCO COOMEVA S.A.', 
		BAN_DIRECCION=UPPER('KR 18 # 84-14 Bogotá D.C.') 
	WHERE BAN_CODIGO='21'
	PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 21 POR: BANCO COOMEVA S.A.' 
END
/*08) Atualizacion de  BANCO COOPERATIVO COOPCENTRAL*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='62')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('62',UPPER('BANCO COOPERATIVO COOPCENTRAL'),UPPER('Avenida Calle 116 No. 23-06/28 Edificio Business Center 116 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 62: BANCO COOPERATIVO COOPCENTRAL'
	END
/*09) Atualizacion de  BANCO COOPERATIVO COOPCENTRAL*/
IF EXISTS (SELECT * FROM MAESTRO_BANCOS WHERE BAN_CODIGO='62')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO DE BOGOTÁ', 
			BAN_DIRECCION=UPPER('Calle 36 No. 7-47 Bogotá D.C.') 
		WHERE BAN_CODIGO='01'
  PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 01 POR: BANCO DE BOGOTÁ' 
END

/*10) Atualizacion de  BANCAMIA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='31')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO DE LAS MICROFINANZAS – BANCAMÍA S.A.', 
			BAN_DIRECCION=UPPER('Carrera 9 No. 66-25 Bogotá D.C.') 
		WHERE BAN_CODIGO='31'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 31 POR: BANCO DE LAS MICROFINANZAS – BANCAMÍA S.A.' 
	END
/*11) Atualizacion de  BANCO DE OCCIDENTE*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='23')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO DE OCCIDENTE S.A.', 
			BAN_DIRECCION=UPPER('Carrera 13 No. 27-47 Bogotá, D.C.') 
		WHERE BAN_CODIGO='23'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 23 POR: BANCO DE OCCIDENTE S.A.' 
	END
/*12) Atualizacion de BANCO FALABELLA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='60')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
			SET BAN_NOMBRE='BANCO FALABELLA S.A.', 
				BAN_DIRECCION=UPPER('Avenida 19 No. 120-71 Piso 3 Bogotá D.C.') 
			WHERE BAN_CODIGO='60'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 60 POR: BANCO FALABELLA S.A.' 
	END

/*13) Atualizacion de BANCO FINANDINA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='24')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO FINANDINA S.A.', 
			BAN_DIRECCION=UPPER('Kilómetro 17 carretera central del Norte vía Chía Chía - Cundinamarca ') 
		WHERE BAN_CODIGO='24'
	PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 24 POR: BANCO FINANDINA S.A.' 
  END

/*14) Atualizacion de BANCO SUDAMERIS*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='12')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO GNB SUDAMERIS S.A.', 
			BAN_DIRECCION=UPPER('Carrera 7 No. 75-85 / 87 Bogotá D.C.') 
		WHERE BAN_CODIGO='12'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 12 POR: BANCO GNB SUDAMERIS S.A.' 
	END

/*15) Atualizacion de BANCO ITAU CORPBANCA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='08')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
			SET BAN_NOMBRE='BANCO ITAÚ CORPBANCA COLOMBIA S.A', 
				BAN_DIRECCION=UPPER('Carrera 7 No. 99-53 Bogotá D.C.') 
				WHERE BAN_CODIGO='08'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 08 POR: BANCO ITAÚ CORPBANCA COLOMBIA S.A' 
	END

/*16) Atualizacion de BANCO MULTIBANK*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='63')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('63',UPPER('BANCO MULTIBANK S.A.'),UPPER('Carrera 7 No. 73-47 PISO 6 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 63: BANCO MULTIBANK S.A.'
	END

/*17) Actualizacion de BANCO MUNDO MUJER*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='64')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('64',UPPER('BANCO MUNDO MUJER S.A.'),UPPER('Carrera 11 No. 5-56 POPAYÁN - CAUCA')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 64: BANCO MUNDO MUJER S.A.'
	END

/*18) Actualizacion de BANCO PICHINCHA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='27')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO PICHINCHA S.A.', 
			BAN_DIRECCION=UPPER('Carrera 11 No. 92-09 Bogotá D.C.') WHERE 
			BAN_CODIGO='27'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 27 POR: BANCO PICHINCHA S.A.' 
	END

/*19) Actualizacion de BANCO POPULAR*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='02')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO POPULAR', 
			BAN_DIRECCION=UPPER('Calle 17 No. 7–35 / 43 Bogotá D.C.') 
		WHERE BAN_CODIGO='02'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 02 POR: BANCO POPULAR' 
	END

/*20) Actualizacion de BANCO PROCREDIT*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='28')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO PROCREDIT', 
			BAN_DIRECCION=UPPER('AV. CALLE 39 No. 13A-16 Bogotá D.C.') 
		WHERE BAN_CODIGO='28'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 28 POR: BANCO PROCREDIT' 
	END

/*21) Actualizacion de BANCO PROCREDIT*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='06')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCO SANTANDER DE NEGOCIOS COLOMBIA S.A', 
			BAN_DIRECCION=UPPER('Calle 93A No. 13-24 Piso 4 Bogotá D.C.') 
		WHERE BAN_CODIGO='06'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 06 POR: BANCO SANTANDER DE NEGOCIOS COLOMBIA S.A' 
	END

/*22) Actualizacion de BANCOLOMBIA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='03')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='BANCOLOMBIA S.A.', 
			BAN_DIRECCION=UPPER('CL 30A # 6-65 Bogotá D.C.') 
		WHERE BAN_CODIGO='03'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 03 POR: BANCOLOMBIA S.A.' 
	END

/*23) Actualizacion de BANCO BBVA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='13')
	BEGIN 
		UPDATE MAESTRO_BANCOS
		SET BAN_NOMBRE='BBVA COLOMBIA', 
			BAN_DIRECCION=UPPER('Carrera 9 No. 72-21 Bogotá D.C.') 
		WHERE BAN_CODIGO='13'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 13 POR: BBVA COLOMBIA' 
	END

/*24) Actualizacion de CITYBANK*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='09')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='CITIBANK', 
			BAN_DIRECCION=UPPER('Carrera 9A No. 99-02 Piso 3 Bogotá D.C.') 
			WHERE BAN_CODIGO='09'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 09 POR: CITIBANK' 
	END

/*25) ACTUALIZACION DEL BANCO DAVIVIENDA*/
IF EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='34')
	BEGIN 
		UPDATE MAESTRO_BANCOS  
		SET BAN_NOMBRE='DAVIVIENDA', 
			BAN_DIRECCION=UPPER('Avenida El Dorado No. 68C-61 Piso 10 Bogotá, D.C.') 
		WHERE BAN_CODIGO='34'
		PRINT 'SE ACTUALIZAN DATOS DEL BANCO CON CODIGO 34 POR: DAVIVIENDA' 
	END

/*26) ACTUALIZACION DE LA CAMARA DE COMERCIO*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='65')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('65',UPPER('CÁMARA DE COMERCIO DE BOGOTÁ'),UPPER('Avenida El Dorado No. 68D-35 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 65: CÁMARA DE COMERCIO DE BOGOTÁ'
	END

/*27) ACTUALIZACION DEL DEPÓSITO CENTRALIZADO DE VALORES DE COLOMBIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='66')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('66',UPPER('DEPÓSITO CENTRALIZADO DE VALORES DE COLOMBIA DECEVAL S.A.'),UPPER('Avenida Calle 26 No. 59–51 Torre 3 Oficina 501 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 66: DEPÓSITO CENTRALIZADO DE VALORES DE COLOMBIA DECEVAL S.A.'
	END

/*28) ACTUALIZACION DE LA COOPERATIVA FINANCIERA DE ANTIOQUIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='67')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('67',UPPER('COOPERATIVA FINANCIERA DE ANTIOQUIA'),UPPER('Carrera 43A No. 31-159 Local 202 Edificio Gruval Piso 2 Medellín - Antioquia.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 67: COOPERATIVA FINANCIERA DE ANTIOQUIA'
	END

/*29) ACTUALIZACION DE LA COOPERATIVA FINANCIERA JOHN F. KENNEDY*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='68')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('68',UPPER('COOPERATIVA FINANCIERA JOHN F. KENNEDY'),UPPER('Carrera 51 No. 43-24 Medellín - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 68: COOPERATIVA FINANCIERA JOHN F. KENNEDY'
	END

/*30) ACTUALIZACION DE LA COOPERATIVA FINANCIERA COOFINEP*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='69')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('69',UPPER('COOPERATIVA FINANCIERA COOFINEP'),UPPER('Calle 30 No. 43-45 Local 101 Medellín - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 69: COOPERATIVA FINANCIERA COOFINEP'
	END
/*31) ACTUALIZACION DE LA COOPERATIVA FINANCIERA COTRAFA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='70')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('70',UPPER('COOPERATIVA FINANCIERA COTRAFA'),UPPER('Calle 46 No. 49-146 Bello - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 70: COOPERATIVA FINANCIERA COTRAFA'
	END

/*32) ACTUALIZACION DE LA COOPERATIVA FINANCIERA - CONFIAR*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='71')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('71',UPPER('COOPERATIVA FINANCIERA - CONFIAR'),UPPER('Calle 52 (Avenida 1o. de Mayo) No. 49-40 Piso 2 Medellín - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 71: COOPERATIVA FINANCIERA - CONFIAR'
	END
/*33) ACTUALIZACION DE LA COMPAÑIA DE FINANCIAMIENTO DE GIROS Y FINANZAS*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='72')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
	VALUES
		('72',UPPER('COMPAÑÍA DE FINANCIAMIENTO GIROS & FINANZAS'),UPPER('Calle 4 No. 27-52 Cali - Valle')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 72: COMPAÑÍA DE FINANCIAMIENTO GIROS & FINANZAS'
	END
/*34) COMPAÑÍA DE FINANCIAMIENTO COLTEFINANCIERA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='73')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('73',UPPER('COMPAÑÍA DE FINANCIAMIENTO COLTEFINANCIERA'),UPPER('Calle 52 No. 47-42 Pisos 11 y 12 Medellín - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 73: COMPAÑÍA DE FINANCIAMIENTO COLTEFINANCIERA'
	END
/*35) ACTUALIZACION DE COMPAÑÍA DE FINANCIAMIENTO DANN REGIONAL*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='74')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('74',UPPER('COMPAÑÍA DE FINANCIAMIENTO DANN REGIONAL'),UPPER('Carrera 43A No. 7-50 Piso 17 Torre Financiera Dann Medellín - Antioquia')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 74: COMPAÑÍA DE FINANCIAMIENTO DANN REGIONAL'	
	END

/*36) ACTUALIZACION DE COMPAÑÍA DE FINANCIAMIENTO CREDIFINANCIERA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='75')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('75',UPPER('COMPAÑÍA DE FINANCIAMIENTO CREDIFINANCIERA'),UPPER('Carrera 10 No. 64-44 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 75: COMPAÑÍA DE FINANCIAMIENTO CREDIFINANCIERA'
	END

/*37) ACTUALIZACION DE LA COMPAÑÍA DE FINANCIAMIENTO PAGOS INTERNACIONALES*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='76')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('76',UPPER('COMPAÑÍA DE FINANCIAMIENTO PAGOS INTERNACIONALES'),UPPER('Calle 5 No. 50-103 Ciudadela Comercial Cosmocentro, Local 245 Cali - Valle.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 76: COMPAÑÍA DE FINANCIAMIENTO PAGOS INTERNACIONALES'
	END

/*38) ACTUALIZACION DE OICOLOMBIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='77')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('77',UPPER('COMPAÑÍA DE FINANCIAMIENTO OICOLOMBIA'),UPPER('Calle 70 No. 7-30 Piso 9 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 77: COMPAÑÍA DE FINANCIAMIENTO OICOLOMBIA'
	END

/*39) ACTUALIZACION DE COMPAÑÍA DE FINANCIAMIENTO LA HIPOTECARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='78')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('78',UPPER('COMPAÑÍA DE FINANCIAMIENTO LA HIPOTECARIA'),UPPER('Carrera 13 No. 93-40 Of. 210 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 78: COMPAÑÍA DE FINANCIAMIENTO LA HIPOTECARIA'
	END

/*40) ACTUALIZACION DE JURISCOOP*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='79')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('79',UPPER('COMPAÑÍA DE FINANCIAMIENTO JURISCOOP'),UPPER('Avenida Calle 26 No. 69D-91 Torre Avenida el Dorado, Piso 10, Centro Empresarial Arrecife Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 79: COMPAÑÍA DE FINANCIAMIENTO JURISCOOP'
	END

/*41) ACTUALIZACION DE BBVA FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='80')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('80',UPPER('BBVA FIDUCIARIA'),UPPER('Carrera 9 No. 72-21 Piso 9 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 80: BBVA FIDUCIARIA'
	END

/*42) ACTUALIZACION DE ITAÚ SECURITIES SERVICES COLOMBIA SOCIEDAD FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='81')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('81',UPPER('ITAÚ SECURITIES SERVICES COLOMBIA SOCIEDAD FIDUCIARIA'),UPPER('Carrera 7 No. 99-21 Piso 17 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 81: ITAÚ SECURITIES SERVICES COLOMBIA SOCIEDAD FIDUCIARIA'
	END

/*43) ACTUALIZACION DE FIDUCIARIA COLMENA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='82')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('82',UPPER('FIDUCIARIA COLMENA'),UPPER('Calle 72 No. 10-71 Piso 3 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 82: FIDUCIARIA COLMENA'
	END

/*44) ACTUALIZACION DE OLD MUTUAL SOCIEDAD FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='83')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('83',UPPER('OLD MUTUAL SOCIEDAD FIDUCIARIA'),UPPER('Avenida 19 No. 109A-30 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 83: OLD MUTUAL SOCIEDAD FIDUCIARIA'
	END

/*45) ACTUALIZACION DE ALIZANZA FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='85')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
	VALUES
		('85',UPPER('ALIZANZA FIDUCIARIA'),UPPER('Carrera 15 No. 82-99 Piso 3 Bogotá D.C.')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 85: ALIZANZA FIDUCIARIA'
END

/*46) ACTUALIZACION DE FIDUCIARIA POPULAR S.A. -FIDUCIAR S.A*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='86')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('86',UPPER('FIDUCIARIA POPULAR S.A. -FIDUCIAR S.A'),UPPER('Carrera 13A No. 29-24 Pisos 20 y 21 Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 86: FIDUCIARIA POPULAR S.A. -FIDUCIAR S.A'
	END
	
/*47) ACTUALIZACION DE FIDUCIARIA CORFICOLOMBIANA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='87')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('87',UPPER('FIDUCIARIA CORFICOLOMBIANA'),UPPER('Carrera 13 No. 26-45 Piso 14 Edificio Internacional Bogotá D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 87: FIDUCIARIA CORFICOLOMBIANA'
	END

/*48) ACTUALIZACION DE FIDUCIARIA POPULAR S.A. -FIDUCIAR S.A*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='88')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('88',UPPER('FIDUCIARIA DE OCCIDENTE'),UPPER('Carrera 13 No. 27-47 Piso 9 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 88: FIDUCIARIA DE OCCIDENTE'
	END

/*49) ACTUALIZACION DE FIDUCIARIA BOGOTÁ*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='89')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('89',UPPER('FIDUCIARIA BOGOTÁ'),UPPER('Calle 67 No. 7-37 Piso 3 Edificio Plaza 67 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 89: FIDUCIARIA BOGOTÁ'
	END

/*50) ACTUALIZACION DE FIDUCIARIA BOGOTÁ*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='90')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('90',UPPER('ITAÚ ASSET MANAGEMENT COLOMBIA S.A. SOCIEDAD FIDUCIARIA'),UPPER('Carrera 7 No. 27-18 Piso 19 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 90: ITAÚ ASSET MANAGEMENT COLOMBIA S.A. SOCIEDAD FIDUCIARIA'
	END

/*51) ACTUALIZACION DE FIDUCIARIA CITITRUST COLOMBIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='91')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('91',UPPER('FIDUCIARIA CITITRUST COLOMBIA'),UPPER('Carrera 9 No. 99-02 Piso 1 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 91: FIDUCIARIA CITITRUST COLOMBIA'
	END

/*52) ACTUALIZACION DE FIDUCIARIA COLPATRIA*/
	IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='92')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('92',UPPER('FIDUCIARIA COLPATRIA'),UPPER('Carrera 7 No. 24-89 Piso 21 Bogotá, D.C.')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 92: FIDUCIARIA COLPATRIA'END

/*53) ACTUALIZACION DE FIDUCIARIA BANCOLOMBIA*/ 
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='93')
	BEGIN 
	INSERT INTO [dbo].[MAESTRO_BANCOS]
	([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
	VALUES
	('93',UPPER('FIDUCIARIA BANCOLOMBIA'),UPPER('Carrera 48 No. 26-85. Av. Los Industriales. Dirección General, Torre Sur, Piso 6E. Medellín - Antioquía')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 93: FIDUCIARIA BANCOLOMBIA'
END

/*54) ACTUALIZACION DE ACCION FIDUCIARIA*/ 
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='94')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('94',UPPER('ACCION FIDUCIARIA'),UPPER('Calle 85 No. 9-65 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 94: ACCION FIDUCIARIA'
	END

/*55) ACTUALIZACION DE FIDUCIARIA  SERVITRUST GNB SUDAMERIS*/ 
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='95')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('95',UPPER('FIDUCIARIA SERVITRUST GNB SUDAMERIS'),UPPER('Carrera 7 No. 75-85/87 Piso 10 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 95: FIDUCIARIA SERVITRUST GNB SUDAMERIS'
	END

/*56) ACTUALIZACION DE FIDUCIARIA CENTRAL*/ 
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='96')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('96',UPPER('FIDUCIARIA CENTRAL'),UPPER('Avenida El Dorado No. 69A-51 Interior 3 Piso 3 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 96: FIDUCIARIA CENTRAL'
	END

/*57) ACTUALIZACION DE SOCIEDAD FIDUCIARIA DE DESARROLLO AGROPECUARIO*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='97')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('97',UPPER('SOCIEDAD FIDUCIARIA DE DESARROLLO AGROPECUARIO'),UPPER('Calle 16 No. 6-16 Piso 29 Edificio Avianca Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 97: SOCIEDAD FIDUCIARIA DE DESARROLLO AGROPECUARIO'
	END

/*58) ACTUALIZACION DE SOCIEDAD FIDUCOLDEX*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='98')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('98',UPPER('FIDUCOLDEX'),UPPER('Calle 28 No. 13A-24, Piso 6o y 7o , Edificio el Museo Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 98: FIDUCOLDEX'
	END

/*59) ACTUALIZACION DE FIDUCIARIA DAVIVIENDA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='99')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('99',UPPER('FIDUCIARIA DAVIVIENDA'),UPPER('Avenida el Dorado No 68B-85 Piso 2 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 99: FIDUCIARIA DAVIVIENDA'
	END
	
/*60) ACTUALIZACION DE FIDUGESTION*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='35')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('35',UPPER('FIDUGESTION'),UPPER('Calle 10 No. 4-40 Of. 705 Edificio Bolsa de Occidente Cali - Valle')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 35: FIDUGESTION'
   END

/*61) ACTUALIZACION DE CREDICORP CAPITAL FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='37')BEGIN INSERT INTO [dbo].[MAESTRO_BANCOS]
	([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
	VALUES
	('37',UPPER('CREDICORP CAPITAL FIDUCIARIA'),UPPER('Calle 34 No. 6-61 Piso 2 Bogotá, D.C.')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 37: CREDICORP CAPITAL FIDUCIARIA'
END

/*62) ACTUALIZACION DE BNP PARIBAS SECURITIES SERVICES FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='39')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('39',UPPER('BNP PARIBAS SECURITIES SERVICES FIDUCIARIA'),UPPER('Carrera 11 No. 77A-65 Oficina 203 204 Edf. Semana Bogotá, D.C. ')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 39: BNP PARIBAS SECURITIES SERVICES FIDUCIARIA'
	END

/*63) ACTUALIZACION DE BTG PACTUAL FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='41')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('41',UPPER('BTG PACTUAL FIDUCIARIA'),UPPER('Carrera 43a No. 1-50, San Fernando Plaza, Torre 2, Piso 12 Medellín - Antioquía')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 41: BTG PACTUAL FIDUCIARIA'
	END

/*64) ACTUALIZACION DE FIDUCIARIA COOMEVA*/
	IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='42')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('42',UPPER('FIDUCIARIA COOMEVA'),UPPER('Calle 13 No. 57-50 Piso 3 Cali - Valle')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 42: FIDUCIARIA COOMEVA'
	END

/*65) ACTUALIZACION DE RENTA 4 & GLOBAL FIDUCIARIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='43')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
	VALUES
		('43',UPPER('RENTA 4 & GLOBAL FIDUCIARIA'),UPPER('Carrera 9 No. 78-15 Bogotá, D.C.')) 
		PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 43: RENTA 4 & GLOBAL FIDUCIARIA'
	END

/*66) ACTUALIZACION DE SANTANDER SECURITIES SERVICES COLOMBIA*/
IF NOT EXISTS (SELECT 1 FROM MAESTRO_BANCOS WHERE BAN_CODIGO='44')
	BEGIN 
		INSERT INTO [dbo].[MAESTRO_BANCOS]
		([BAN_CODIGO],[BAN_NOMBRE],[BAN_DIRECCION])
		VALUES
		('44',UPPER('SANTANDER SECURITIES SERVICES COLOMBIA'),UPPER('Calle 93 A No. 13-24 Oficina 301 Bogotá D.C.')) 
	PRINT 'SE AGREGAN DATOS DEL BANCO CON CODIGO 44: SANTANDER SECURITIES SERVICES COLOMBIA'
END

--Caso 298554
DECLARE @MaxTiposTitulo AS CHAR(2) = (SELECT MAX(codigo) + 1 FROM TIPOS_TITULO)
INSERT INTO TIPOS_TITULO (codigo, nombre) VALUES(@MaxTiposTitulo, 'APORTE PATRONAL TERRITORIAL');