

CREATE TABLE [dbo].[CONTEXTO_TRANSACCIONAL](
	[ID_CONTEXTO] [int] IDENTITY(1,1) NOT NULL,
	[ID_TX] [varchar](50) NULL,
	[FECHA_INICIO] [datetime] NOT NULL,
	[ID_DEF_PROCESO] [varchar](50) NULL,
	[NOMBRE_PROCESO] [varchar](50) NULL,
	[ID_USUARIO_APP] [varchar](50) NOT NULL,
	[ID_EMISOR] [varchar](50) NOT NULL,
	[FECHA_CREACION] [datetime] NOT NULL,
	[ID_TITULO] [int] NOT NULL,
	[COD_TX]  [varchar](50)  NOT NULL,
 CONSTRAINT [PK_CONTEXTO_TRANSACCIONAL] PRIMARY KEY CLUSTERED 
(
	[ID_CONTEXTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SP_CONTEXTO_TRANSACCIONAL]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
DROP PROCEDURE [dbo].[SP_CONTEXTO_TRANSACCIONAL]
END
GO
-- =============================================
-- Author:		Stefanini - Oscar Diaz
-- Create date: 2018-11-7
-- Description:	Crea / actualiza el contexto transaccional
-- =============================================
CREATE PROCEDURE [dbo].[SP_CONTEXTO_TRANSACCIONAL]
@ID_TX varchar(50),
@FECHA_INICIO datetime,
@ID_DEF_PROCESO varchar(50),
@NOMBRE_PROCESO varchar(50),
@ID_USUARIO_APP varchar(50),
@ID_EMISOR varchar(50),
@ID_TITULO int,
@COD_TX varchar(50)
AS
BEGIN

SET NOCOUNT ON;
--Verificación de existencia
IF NOT EXISTS (SELECT TOP 1
		1
	FROM dbo.CONTEXTO_TRANSACCIONAL
	WHERE ID_TX = @ID_TX
	AND FECHA_INICIO = @FECHA_INICIO
	AND ID_DEF_PROCESO = @ID_DEF_PROCESO
	AND [NOMBRE_PROCESO] = @NOMBRE_PROCESO
	AND [ID_EMISOR] = @ID_EMISOR)
BEGIN

INSERT INTO [dbo].[CONTEXTO_TRANSACCIONAL] ([ID_TX]
, [FECHA_INICIO]
, [ID_DEF_PROCESO]
, [NOMBRE_PROCESO]
, [ID_USUARIO_APP]
, [ID_EMISOR]
, [FECHA_CREACION]
, [ID_TITULO]
,[COD_TX])
	VALUES (@ID_TX, @FECHA_INICIO, @ID_DEF_PROCESO, @NOMBRE_PROCESO, @ID_USUARIO_APP, @ID_EMISOR, GETDATE(), @ID_TITULO, @COD_TX)
END
ELSE
UPDATE [dbo].[CONTEXTO_TRANSACCIONAL]
   SET [ID_TX] = @ID_TX
      ,[FECHA_INICIO] = @FECHA_INICIO
      ,[ID_DEF_PROCESO] = @ID_DEF_PROCESO
      ,[NOMBRE_PROCESO] = @NOMBRE_PROCESO
      ,[ID_USUARIO_APP] = @ID_USUARIO_APP
      ,[ID_EMISOR] = @ID_EMISOR
      ,[ID_TITULO] = @ID_TITULO
	  ,COD_TX =  @COD_TX 
WHERE ID_TX = @ID_TX
	AND FECHA_INICIO = @FECHA_INICIO
	AND ID_DEF_PROCESO = @ID_DEF_PROCESO
	AND [NOMBRE_PROCESO] = @NOMBRE_PROCESO
	AND [ID_EMISOR] = @ID_EMISOR



END
