/*
Nombre		:	SP_ALMACENAMIENTO_TEMPORAL_ACTUALIZAR
Descripcion	:	Se actualiza el registro
Parametros	:	@ID_TAREA_ASIGNADA AS BIGINT	ID DE LA TAREA
				@JSON_OBJ AS varchar(max) JSON DEL OBJETO

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_ALMACENAMIENTO_TEMPORAL_ACTUALIZAR]
	@ID_TAREA_ASIGNADA AS BIGINT,
	@JSON_OBJ AS varchar(max)     
AS
UPDATE [dbo].[ALMACENAMIENTO_TEMPORAL] 
   SET [JSON_OBJ] = @JSON_OBJ,
       [FEC_ACTUALIZACION] = GETDATE()
 WHERE ID_TAREA_ASIGNADA = @ID_TAREA_ASIGNADA
GO


