/*
Nombre		:	SP_ALMACENAMIENTO_TEMPORAL_POR_IDTAREA
Descripcion	:	Se consulta la tabla de almacenamiento temporal por el id de tarea
Parametros	:	@ID_TAREA_ASIGNADA AS BIGINT	ID DE LA TAREA

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_ALMACENAMIENTO_TEMPORAL_POR_IDTAREA]
	@ID_TAREA_ASIGNADA AS BIGINT
AS
	SELECT  T.[ID_ALMACENAMIENTO_TEMPORAL] ,
			T.[JSON_OBJ] ,
			T.[ID_TAREA_ASIGNADA],
			T.[FEC_ACTUALIZACION]		
	FROM ALMACENAMIENTO_TEMPORAL T	
	WHERE T.[ID_TAREA_ASIGNADA] = @ID_TAREA_ASIGNADA
	
GO