/*
Nombre		:	SP_DOMINIO_DETALLE_DOMINIOID
Descripcion	:	Se consulta detalles dominio por el dominio id
Parametros	:	@ID_DOMINIO AS INT id del dominio a consultar

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_DOMINIO_DETALLE_DOMINIOID]
	@ID_DOMINIO AS INT
AS
	SELECT  D.[ID_DOMINIO_DETALLE],
			D.[ID_DOMINIO],
			D.[VAL_NOMBRE],
			D.[DESC_DESCRIPCION],
			D.[VAL_VALOR]
	FROM DOMINIO_DETALLE D	
	WHERE D.ID_DOMINIO = @ID_DOMINIO	
GO
