/*
Nombre		:	SP_DOCUMENTOS_TIPO_TITULO
Descripcion	:	Se consulta los tipos de documento por tipo de titulo
Parametros	:	@COD_TIPO_TITULO	AS CHAR(2)	Tipo del titulo

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_DOCUMENTOS_TIPO_TITULO]
	@COD_TIPO_TITULO		AS CHAR(2)
AS
	 SELECT DT.[ID_DOCUMENTO_TITULO],D.NOMBRE_DOCUMENTO,DT.[COD_TIPO_TITULO],DT.[VAL_ESTADO],DT.[VAL_OBLIGATORIO]
	 FROM [dbo].[DOCUMENTO_TITULO] D
		INNER JOIN [dbo].[DOCUMENTO_TITULO_TIPO_TITULO] DT ON D.ID_DOCUMENTO_TITULO =DT.ID_DOCUMENTO_TITULO
	 WHERE DT.[COD_TIPO_TITULO]=@COD_TIPO_TITULO
	
GO
