/*
Nombre		:	SP_FUENTE_DIRECCIONES
Descripcion	:	Consulta todas las fuentes de direcciones
Parametros	:	

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_FUENTE_DIRECCIONES]
AS
	 SELECT F.ID_FUENTE_DIRECCION,F.DES_NOMBRE_FUENTE_DIRECCION FROM FUENTE_DIRECCION F
GO
