-- =============================================
-- Author: Eduar Fabian Hernandez Nieves
-- Create date: 2018-11-14
-- Description: Carga los títulos para el festor de estudio de títulos
--- EXEC [SP_ObtenerTitulosEstudioTitulos] 'MFONG','',0,0,'','','',''
-- =============================================

CREATE PROCEDURE [dbo].[SP_ObtenerTitulosEstudioTitulos] 
   @USULOG AS VARCHAR(20), -- Usuario al cual se le asigno la tarea
   @NROTITULO AS VARCHAR(50) , -- Número de título
   @ESTADOPROCESAL AS INT,
   @ESTADOSOPERATIVO AS INT,
   @FCHENVIOCOBRANZADESDE AS VARCHAR(10),
   @FCHENVIOCOBRANZAHASTA AS VARCHAR(10),
   @NROIDENTIFICACIONDEUDOR AS VARCHAR(50),
   @NOMBREDEUDOR AS VARCHAR (50)
   AS
   
BEGIN                     
      
SET NOCOUNT ON 

		   SELECT 
		   TA.ID_TAREA_ASIGNADA AS IDUNICO,
		   TA.ID_TAREA_ASIGNADA,
		   MT.MT_nro_titulo AS NROTITULO,
			CONVERT(VARCHAR(10),MT.MT_fec_expedicion_titulo,103) AS FCHEXPEDICIONTITULO,
		   ED.ED_Nombre AS NOMBREDEUDOR,
		   ED.ED_Codigo_Nit AS NRONITCEDULA,
		   TT.nombre AS TIPOOBLIGACION,
		   MT.totaldeuda AS TOTALOBLIGACION,
		   CONVERT(VARCHAR(10),TA.FEC_ENTREGA_GESTOR,103) AS FEC_ENTREGA_GESTOR, 
		   CONVERT(VARCHAR(10),FEC_ENTREGA_GESTOR +  TT.DIAS_MAX_GESTION_ROJO,103)  AS FCHLIMITE, 
		   CASE WHEN DATEDIFF(DAY ,FEC_ENTREGA_GESTOR  ,GETDATE()) >=  TT.DIAS_MAX_GESTION_ROJO THEN 'ROJO' 
		        WHEN DATEDIFF(DAY ,FEC_ENTREGA_GESTOR  ,GETDATE()) >= TT.DIAS_MAX_GESTION_AMARILLO  AND  DATEDIFF(DAY ,FEC_ENTREGA_GESTOR  ,GETDATE()) <  TT.DIAS_MAX_GESTION_ROJO  THEN 'AMARILLO'END
		    AS COLOR,
		   EO.ID_ESTADO_OPERATIVOS,
		   TA.VAL_PRIORIDAD

		   FROM TAREA_ASIGNADA TA
			LEFT JOIN [dbo].[ESTADO_OPERATIVO] EO WITH (NOLOCK) ON TA.COD_ESTADO_OPERATIVO = EO.ID_ESTADO_OPERATIVOS
			LEFT JOIN MAESTRO_TITULOS MT WITH (NOLOCK) ON MT.idunico = TA.ID_UNICO_TITULO
			LEFT JOIN [dbo].[TIPOS_TITULO] TT WITH (NOLOCK) ON TT.codigo = MT.MT_tipo_titulo
			LEFT JOIN [dbo].[DEUDORES_EXPEDIENTES] DE WITH (NOLOCK) ON MT.idunico = DE.ID_MAESTRO_TITULOS
			LEFT JOIN [dbo].[ENTES_DEUDORES] ED WITH (NOLOCK) ON DE.deudor = ED.ED_Codigo_Nit
			
			WHERE 
			MT.MT_expediente IS NULL AND
			TA.ID_UNICO_TITULO IS NOT NULL AND
			((@USULOG IS NULL) OR (VAL_USUARIO_NOMBRE = @USULOG)) AND
			((@NROTITULO = '') OR (MT.MT_nro_titulo = @NROTITULO)) AND
			--((@ESTADOPROCESAL IS NULL) OR (col3 = @ESTADOPROCESAL))
			((@ESTADOSOPERATIVO = 0) OR (EO.ID_ESTADO_OPERATIVOS = @ESTADOSOPERATIVO)) AND
			((@FCHENVIOCOBRANZADESDE = '') OR (TA.FEC_ENTREGA_GESTOR >= @FCHENVIOCOBRANZADESDE)) AND
			((@FCHENVIOCOBRANZAHASTA = '') OR (TA.FEC_ENTREGA_GESTOR <= @FCHENVIOCOBRANZAHASTA)) AND
			((@NROIDENTIFICACIONDEUDOR = '') OR (ED.ED_Codigo_Nit = @NROIDENTIFICACIONDEUDOR)) AND
			((@NOMBREDEUDOR = '') OR (ED.ED_Nombre = @NOMBREDEUDOR))
			AND TA.COD_ESTADO_OPERATIVO = 4
			ORDER BY TA.VAL_PRIORIDAD DESC, MT.fechaRevoca ASC, MT.MT_fec_expedicion_titulo ASC 
 END
GO
