/*
Nombre		:	SP_TAREA_ASIGNADA_POR_ID
Descripcion	:	Consulta una tarea por su id 
Parametros	:	@ID_TAREA_ASIGNADA AS BIGINT id de la tarea

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_TAREA_ASIGNADA_POR_ID]
	@ID_TAREA_ASIGNADA AS BIGINT
AS
	SELECT  T.[ID_TAREA_ASIGNADA] ,
			T.[VAL_USUARIO_NOMBRE] ,
			T.[COD_TIPO_OBJ] ,
			T.[ID_UNICO_TITULO] ,
			T.[EFINROEXP_EXPEDIENTE] ,
			T.[FEC_ACTUALIZACION] ,
			T.[FEC_ENTREGA_GESTOR] ,
			T.[VAL_PRIORIDAD] ,
			T.[COD_ESTADO_OPERATIVO] 
	FROM TAREA_ASIGNADA T	
	WHERE T.[ID_TAREA_ASIGNADA] = @ID_TAREA_ASIGNADA
	
GO