/*
Nombre		:	SP_TAREA_ASIGNADA_INGRESAR
Descripcion	:	Se crea un registro

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/19		OSCAR GONZALEZ 			CREACION
*/

CREATE PROCEDURE [dbo].[SP_TAREA_ASIGNADA_INGRESAR]
	@VAL_USUARIO_NOMBRE AS varchar(50),
	@COD_TIPO_OBJ AS int,
	@ID_UNICO_TITULO AS bigint = NULL,
	@EFINROEXP_EXPEDIENTE AS varchar(12) = NULL,
	@VAL_PRIORIDAD AS int,
	@COD_ESTADO_OPERATIVO AS int 
AS
	 INSERT INTO [dbo].[TAREA_ASIGNADA]
           (VAL_USUARIO_NOMBRE
           ,COD_TIPO_OBJ
           ,ID_UNICO_TITULO
           ,EFINROEXP_EXPEDIENTE
           ,FEC_ACTUALIZACION
           ,VAL_PRIORIDAD
           ,COD_ESTADO_OPERATIVO)
     VALUES
	 (@VAL_USUARIO_NOMBRE,@COD_TIPO_OBJ,ISNULL(@ID_UNICO_TITULO,NULL),ISNULL(@EFINROEXP_EXPEDIENTE,NULL),GETDATE(),@VAL_PRIORIDAD,@COD_ESTADO_OPERATIVO)
	
	SELECT * FROM TAREA_ASIGNADA WHERE ID_TAREA_ASIGNADA= SCOPE_IDENTITY()
GO