/*
Nombre		:	SP_TIPOS_CARTERA_POR_PROCEDENCIA
Descripcion	:	Consulta todos los tipos de cartera por area origen
Parametros	:	@COD_PROCEDENCIA AS INT codigo de area origen

Historia	:
VERSION 	FECHA 			AUTOR 					DESCRIPCION
1.00.000	2018/11/18		OSCAR GONZALEZ 			CREACION
*/
CREATE PROCEDURE [dbo].[SP_TIPOS_CARTERA_POR_PROCEDENCIA]
	@COD_PROCEDENCIA AS INT
AS
	SELECT DISTINCT TC.ID_TIPO_CARTERA,TC.DEC_TIPO_CARTERA FROM TIPO_CARTERA TC 
		INNER JOIN TIPOS_TITULO TT ON TT.ID_TIPO_CARTERA = TC.ID_TIPO_CARTERA  
		INNER JOIN PROCEDENCIA_TITULOS PT ON  PT.codigO = TT.COD_PROCEDENCIA WHERE TT.COD_PROCEDENCIA = @COD_PROCEDENCIA
	
GO
