IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[TIPIFICACION_CNC]')
                    AND type IN ( N'P', N'PC','U' ) ) 

BEGIN 
	DROP TABLE [dbo].[TIPIFICACION_CNC]
END

GO

CREATE TABLE [dbo].[TIPIFICACION_CNC](
	[ID_TIPIFICACIONCNC] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_TIPIFICACION] [bigint]  NOT NULL,
	[ID_UNICO_MT] [bigint] NOT NULL,
	[USUARIO] [varchar](100) NOT NULL,
    [FCHOBSERVACIONES] DATETIME NOT NULL,
	
) 
GO
ALTER TABLE [TIPIFICACION_CNC] 
ADD CONSTRAINT [PK_ID_TIPIFICACIONCNC]
PRIMARY KEY CLUSTERED([ID_TIPIFICACIONCNC] ASC) 

GO





