IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[OBSERVACIONES_CUMPLE_NOCUMPLE]')
                    AND type IN ( N'P', N'PC','U' ) ) 

BEGIN 
	DROP TABLE [dbo].[OBSERVACIONES_CUMPLE_NOCUMPLE]
END

GO

CREATE TABLE [dbo].[OBSERVACIONES_CUMPLE_NOCUMPLE](
	[ID_OBSERVACIONES] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_UNICO_MT] [bigint] NOT NULL,
	[USUARIO] [varchar](100) NOT NULL,
    [FCHOBSERVACIONES] DATETIME NOT NULL,
	[OBSERVACIONES] [varchar](500) NOT NULL,
	[DESTINATARIO] [varchar](100) NOT NULL,
	[CUMPLE_NOCUMPLE] [BIT] NOT NULL
)

ALTER TABLE [OBSERVACIONES_CUMPLE_NOCUMPLE] 
ADD CONSTRAINT [PK_ID_OBSERVACIONES]
PRIMARY KEY CLUSTERED([ID_OBSERVACIONES] ASC) 




