IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[OBSERVACIONESDOC_CUMPLE_NOCUMPLE]')
                    AND type IN ( N'P', N'PC','U' ) ) 

BEGIN 
	DROP TABLE [dbo].[OBSERVACIONESDOC_CUMPLE_NOCUMPLE]
END

GO

CREATE TABLE [dbo].[OBSERVACIONESDOC_CUMPLE_NOCUMPLE](
	[ID_OBSERVACIONESDOC] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_UNICO_MT] [bigint] NOT NULL,
	[ID_DOCUMENTO] [bigint] NOT NULL,
	[USUARIO] [varchar](100) NOT NULL,
	[DESTINATARIO] [varchar](100) NOT NULL,
    [FCHENVIO] DATETIME NOT NULL,
	[OBSERVACIONES] [varchar](500) NOT NULL,
	[CUMPLE_NOCUMPLE] [BIT] NOT NULL
) ON [PRIMARY]

ALTER TABLE [OBSERVACIONESDOC_CUMPLE_NOCUMPLE] 
ADD CONSTRAINT [PK_ID_OBSERVACIONESDOC]
PRIMARY KEY CLUSTERED([ID_OBSERVACIONESDOC] ASC) 
GO





