IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'HISTORICO_CLASIFICACION_MANUAL'))
BEGIN
CREATE TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL]
	(
	ID_REGISTRO_CLASIFICACION_MANUAL int NOT NULL IDENTITY (1, 1),
	ID_EXPEDIENTE varchar(12) NOT NULL,
	ID_USUARIO varchar(4) NOT NULL,
	FECHA datetime NOT NULL,
	PERSONA_JURIDICA bit NULL,
	PERSONA_NATURAL bit NULL,
	PERSONA_VIVA bit NULL,
	MATRICULA_MERCANTIL bit NULL,
	ID_MTD_DOCUMENTO bigint NULL,
	PROCESO_ESPECIAL bit NULL,
	TIPO_PROCESO int NULL,
	BENEFICIO_TRIBUTARIO bit NULL,
	PAGOS_DEUDOR bit NULL,
	NUMERO_RADICADO int NULL,
	OBSERVACIONES varchar(1000) NULL
	)  ON [PRIMARY]

ALTER TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL] ADD CONSTRAINT
	[PK_dbo.HISTORICO_CLASIFICACION_MANUAL] PRIMARY KEY CLUSTERED 
	(
	ID_REGISTRO_CLASIFICACION_MANUAL
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


ALTER TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL] ADD CONSTRAINT
	[FK_dbo.HISTORICO_CLASIFICACION_MANUAL_EJEFISGLOBAL] FOREIGN KEY
	(
	ID_EXPEDIENTE
	) REFERENCES dbo.EJEFISGLOBAL
	(
	EFINROEXP
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL] ADD CONSTRAINT
	[FK_dbo.HISTORICO_CLASIFICACION_MANUAL_USUARIOS] FOREIGN KEY
	(
	ID_USUARIO
	) REFERENCES dbo.USUARIOS
	(
	codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL] ADD CONSTRAINT
	[FK_dbo.HISTORICO_CLASIFICACION_MANUAL_MAESTRO_TITULOS_DOCUMENTOS] FOREIGN KEY
	(
	ID_MTD_DOCUMENTO
	) REFERENCES dbo.MAESTRO_TITULOS_DOCUMENTOS
	(
	ID_MAESTRO_TITULOS_DOCUMENTOS
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

ALTER TABLE dbo.[HISTORICO_CLASIFICACION_MANUAL] ADD CONSTRAINT
	[FK_dbo.HISTORICO_CLASIFICACION_MANUAL_TIPOS_PROCESOS_CONCURSALES] FOREIGN KEY
	(
	TIPO_PROCESO
	) REFERENCES dbo.TIPOS_PROCESOS_CONCURSALES
	(
	codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	

END
GO
