
GO
IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'[dbo].[SP_INGRESAR_DOCUMENTOTITULO_TIPOTITULO]')
                    AND type IN ( N'P', N'PC' ) ) 

BEGIN 
	DROP PROCEDURE [dbo].[SP_INGRESAR_DOCUMENTOTITULO_TIPOTITULO] 
END


GO
-- =============================================
-- Author:		Oscar Diaz
-- Create date: 2018-03-12
-- Description:	Ingresa/actualiza un registro en la relación
-- =============================================
CREATE PROCEDURE [dbo].[SP_INGRESAR_DOCUMENTOTITULO_TIPOTITULO] 
@ID_DOCUMENTO_TITULO AS INT,
@COD_TIPO_TITULO AS VARCHAR(2),
@VAL_ESTADO AS BIT,
@VAL_OBLIGATORIO AS BIT
AS
BEGIN
SET NOCOUNT ON;

	IF EXISTS (SELECT TOP 1
		1
	FROM DOCUMENTO_TITULO_TIPO_TITULO
	WHERE ID_DOCUMENTO_TITULO = @ID_DOCUMENTO_TITULO
	AND COD_TIPO_TITULO = @COD_TIPO_TITULO)
BEGIN

UPDATE [dbo].[DOCUMENTO_TITULO_TIPO_TITULO]
SET [VAL_ESTADO] = @VAL_ESTADO
   ,[VAL_OBLIGATORIO] = @VAL_OBLIGATORIO
WHERE ID_DOCUMENTO_TITULO = @ID_DOCUMENTO_TITULO
AND COD_TIPO_TITULO = @COD_TIPO_TITULO
END
ELSE
INSERT INTO [dbo].[DOCUMENTO_TITULO_TIPO_TITULO] ([ID_DOCUMENTO_TITULO]
, [COD_TIPO_TITULO]
, [VAL_ESTADO]
, [VAL_OBLIGATORIO])
	VALUES (@ID_DOCUMENTO_TITULO, @COD_TIPO_TITULO, @VAL_ESTADO, @VAL_OBLIGATORIO)


END
GO
