'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BandejaTitulos
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''hdnRedirectParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRedirectParent As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''pnlFiltroBandejaTitulos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFiltroBandejaTitulos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblNoTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNoTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoTitulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEstadoOperativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstadoOperativo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEstadoOperativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoOperativo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblNumIdentificacionDeudor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumIdentificacionDeudor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumIdentificacionDeudor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumIdentificacionDeudor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblFechaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fecFechaEnvioTituloInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fecFechaEnvioTituloInicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFechaTituloInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFechaTituloInicio As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''fecFechaEnvioTituloFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fecFechaEnvioTituloFin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFechaTituloFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFechaTituloFin As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblNombreDeudor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreDeudor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNombreDeudor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreDeudor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnExportarGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportarGrid As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblEstadoProcesal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstadoProcesal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlEstadoProcesal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoProcesal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlGridBandejaTitulos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGridBandejaTitulos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''grdBandejaTituloAO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBandejaTituloAO As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PaginadorGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginadorGridView As Global.coactivosyp.paginador
End Class
