'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DatosDocumento
    
    '''<summary>
    '''pnlCargaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCargaDocumento As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HdnExtValidas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnExtValidas As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnModificaDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnModificaDoc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblErrorDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorDatos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUploadDpcumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadDpcumento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnCargarPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCargarPopUp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hlinkViewDocOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkViewDocOut As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblDocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''linkver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkver As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''PnlDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlDoc As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpnlModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblCarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnCargar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCargar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hlinkViewDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkViewDoc As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''HdnPathFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnPathFile As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnIdDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdDoc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''FlUpEvidencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FlUpEvidencias As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblErrorDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorDoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPaginas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPaginas As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblObservacionLegibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacionLegibilidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObservacionLegibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionLegibilidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdAsignarDocumento2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAsignarDocumento2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCerrarCargaDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrarCargaDocumento As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnResultUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnResultUpload As Global.System.Web.UI.WebControls.HiddenField
End Class
