'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AprobarSolicitud
    
    '''<summary>
    '''modalResSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalResSolicitud As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlResSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlResSolicitud As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpnlModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdnTareasSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTareasSolicitud As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnTipoSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTipoSolicitud As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnReload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnReload As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblErrorRespuestaSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorRespuestaSolicitud As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRespuestaSolicitudEnviada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRespuestaSolicitudEnviada As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlGestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGestor As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblGestorAsiganado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGestorAsiganado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlGestorAsignado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGestorAsignado As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblObservacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRespuestaSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRespuestaSolicitud As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqRespuestaSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqRespuestaSolicitud As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''btnAprobarSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAprobarSolicitud As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDenegarSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDenegarSolicitud As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTest As Global.System.Web.UI.WebControls.Button
End Class
