'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SolicitudPriorizacion
    
    '''<summary>
    '''modalPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalPriorizacion As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlPriorizacion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdnIdTareaAsiganada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdTareaAsiganada As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblErrorPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorPriorizacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPriorizacionEnviada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriorizacionEnviada As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCausalPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCausalPriorizacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCausalPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCausalPriorizacion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CausalPriorizacionValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CausalPriorizacionValidator As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''lblObservacionPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacionPriorizacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObservacionPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionPriorizacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqObservacionPriorizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqObservacionPriorizacion As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmdPriorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPriorizar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClose2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnTest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTest2 As Global.System.Web.UI.WebControls.Button
End Class
