ALTER TABLE [dbo].[LOG_AUDITORIA] ADD 
[LOG_NEGOCIO] [varchar] (5000) COLLATE Modern_Spanish_CI_AS NULL
GO


CREATE TABLE [dbo].[TIPO_HOMOLOGACION](
	[ID_TIPO_HOMOLOGACION] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_TIPO_HOMOLOGACION] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_HOMOLOGACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



CREATE TABLE [dbo].[MAESTRO_HOMOLOGACION]
(
	[ID_HOMOLOGACION] [int] IDENTITY (1,1) NOT NULL,
	[ID_TIPO_HOMOLOGACION] [int] NOT NULL,
	[FUENTE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[DESTINO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
	[ACTIVO] [bit] NOT NULL,
	CONSTRAINT [PK_MAESTRO_HOMOLOGACION] PRIMARY KEY CLUSTERED
	(
		[ID_HOMOLOGACION] ASC
	) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY  = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MAESTRO_HOMOLOGACION] ADD CONSTRAINT [FK_MAESTRO_HOMOLOGACION_TIPO_HOMOLOGACION] FOREIGN KEY
	(
		[ID_TIPO_HOMOLOGACION]
	)
	REFERENCES [dbo].[TIPO_HOMOLOGACION]
	(
		[ID_TIPO_HOMOLOGACION]
	)
GO

IF EXISTS ( SELECT * 
            FROM   sysobjects 
            WHERE  id = object_id(N'[dbo].[SP_OBTENER_HOMOLOGACION]') 
                   and OBJECTPROPERTY(id, N'IsProcedure') = 1 )
BEGIN
DROP PROCEDURE [dbo].[SP_OBTENER_HOMOLOGACION]
END
GO
-- =============================================
-- Author:		Stefanini - Oscar Diaz
-- Create date: 2018-11-8
-- Description:	Obtiene datos de homologación
-- =============================================
CREATE PROCEDURE [dbo].[SP_OBTENER_HOMOLOGACION]
	@FUENTE VARCHAR(50),
	@TIPO_HOMOLOGACION  INT
AS
BEGIN
SET NOCOUNT ON;

SELECT TOP 1
	MH.ID_HOMOLOGACION
   ,MH.ID_TIPO_HOMOLOGACION
   ,MH.FUENTE
   ,MH.DESTINO
   ,MH.ACTIVO
FROM dbo.maestro_homologacion mh
INNER JOIN dbo.tipo_homologacion th
	ON th.ID_TIPO_HOMOLOGACION = mh.ID_TIPO_HOMOLOGACION
WHERE mh.ACTIVO = 1
AND mh.ID_TIPO_HOMOLOGACION = @TIPO_HOMOLOGACION
AND mh.FUENTE = @FUENTE
END
GO
