'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditMAESTRO_TITULOS_AORIGEN
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''loading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loading As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager
    
    '''<summary>
    '''urlBandejaAreaOrigen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents urlBandejaAreaOrigen As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''urlBandejaEstudioTitulos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents urlBandejaEstudioTitulos As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''urlBandejaNuevoTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents urlBandejaNuevoTitulo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnMostrarObser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnMostrarObser As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnAutomatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnAutomatico As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnAutomaticoCargue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnAutomaticoCargue As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''divTitleNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTitleNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblNroTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNroTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNuevo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ABack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ABack As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tabs1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PnlInformacionDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlInformacionDocumento As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HdnIdTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdTask As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnExpediente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnExpediente As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnIdEstadoOperativo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdEstadoOperativo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtAutomatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutomatico As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboTipo_Cartera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTipo_Cartera As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboMT_tipo_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMT_tipo_titulo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboMT_tiposentencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMT_tiposentencia As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEFIEXPORIGEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIEXPORIGEN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMT_nro_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_nro_titulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMT_fec_expedicion_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_expedicion_titulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecExpTit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecExpTit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtMT_fec_notificacion_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_notificacion_titulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecNotTit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecNotTit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cboMT_for_notificacion_titulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMT_for_notificacion_titulo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtMT_res_resuelve_reposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_res_resuelve_reposicion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMT_fec_expe_resolucion_reposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_expe_resolucion_reposicion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecExpRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecExpRR As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtMT_fec_not_reso_resu_reposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_not_reso_resu_reposicion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecNotRRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecNotRRR As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cboMT_for_not_reso_resu_reposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMT_for_not_reso_resu_reposicion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtMT_reso_resu_apela_recon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_reso_resu_apela_recon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMT_fec_exp_reso_apela_recon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_exp_reso_apela_recon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecExpRAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecExpRAR As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtMT_fec_not_reso_apela_recon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_not_reso_apela_recon As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecNotRAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecNotRAR As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''cboMT_for_not_reso_apela_recon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMT_for_not_reso_apela_recon As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''chkTituloEjecutoriado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTituloEjecutoriado As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FechaEjecutoriaObligatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaEjecutoriaObligatoria As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblFechaEjecutoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaEjecutoria As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMT_fecha_ejecutoriaObli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fecha_ejecutoriaObli As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecEjecObli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecEjecObli As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''FechaExiLiqObligatoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FechaExiLiqObligatoria As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtMT_fec_exi_liqObli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_exi_liqObli As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnBorraFecExiLObli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBorraFecExiLObli As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtMT_fec_cad_presc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMT_fec_cad_presc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboPROCEDENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPROCEDENCIA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LstNotificaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LstNotificaciones As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''CustomValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''BtnGuardar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardar1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnAdiccionarNot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAdiccionarNot As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCancelar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelar1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tabs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PnlValores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlValores As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tTitulo As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lblNombreTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TblTipoTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TblTipoTitulo As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''trValorObligacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trValorObligacion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtValorObligacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorObligacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trPartidaGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPartidaGlobal As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtPartidaGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartidaGlobal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trSancionOmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSancionOmision As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtSancionOmision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSancionOmision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trSancionMora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSancionMora As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtSancionMora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSancionMora As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trSancionInexactitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSancionInexactitud As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtSancionInexactitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSancionInexactitud As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTotalObligacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalObligacion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalObligacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalObligacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTotalPartidaGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalPartidaGlobal As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalPartidaGlobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPartidaGlobal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTotalSancion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalSancion As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalSancion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalSancion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTotalDeuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTotalDeuda As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalDeuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalDeuda As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator2 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''BtnGuardar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardar2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCancelar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelar2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tabs3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PnlDeudores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlDeudores As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tabs4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTexValidDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTexValidDocument As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HdnExtValidas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnExtValidas As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lsvListaDocumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsvListaDocumentos As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''PnlDocAutomatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlDocAutomatico As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''grdDocAutomatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDocAutomatico As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PaginadorDocAutomatico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginadorDocAutomatico As Global.coactivosyp.paginador
    
    '''<summary>
    '''BtnBuscarDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBuscarDoc As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEnviarTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviarTitulo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnGuardar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardar3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCancelar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelar3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnShowTerminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowTerminar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEliminar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCancelarAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelarAccion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEnviarCalificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviarCalificacion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSuspenderTitulo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnVerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVerInfo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''tabs5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tabs6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabs6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''BtnHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnHide As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpMalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpMalla As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlMalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlMalla As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpnlModalMalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlModalMalla As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMallaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMallaTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMalla As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LsvResul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LsvResul As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''btnCancelarMalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelarMalla As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalPopupBuscarDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalPopupBuscarDocumento As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlBuscar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdBuscar As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblTituto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNoExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNoExp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''grdBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBuscar As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''PaginadorGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaginadorGridView As Global.coactivosyp.paginador
    
    '''<summary>
    '''Lblresultados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lblresultados As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBuscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCerrarBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCerrarBuscar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mp1 As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlJust As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpnlModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlModal As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''TxtJustificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJustificacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblValidaJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidaJust As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnGuardarValidaJust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardarValidaJust As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnObservacionesModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnObservacionesModal As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''UpnlObservaModal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlObservaModal2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''BtnObservacionesModal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnObservacionesModal2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnObservacionesModalCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnObservacionesModalCNC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mp2 As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlDocCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlDocCNC As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpnlDocCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpnlDocCNC As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''grdHistoricoCNCDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdHistoricoCNCDoc As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''TxtComentarioCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtComentarioCNC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblValidaComentarioCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValidaComentarioCNC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnEnviarCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarCNC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCloseCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseCNC As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnModalClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalClasificacion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalClasificacion As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlModalClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModalClasificacion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblMensajeClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeClasificacion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnAceptarClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptarClasificacion As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnErrorValidacionInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnErrorValidacionInicial As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalValidacionInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalValidacionInicial As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''pnlModalValidacionInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModalValidacionInicial As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''uPnlModalValidacionInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uPnlModalValidacionInicial As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblErrorPrioridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorPrioridad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorUsuarioAsignado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorUsuarioAsignado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorNoEsTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorNoEsTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorEstadoOperativoErroneo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorEstadoOperativoErroneo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorTituloClasificado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorTituloClasificado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnRedirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirect As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRedirect2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirect2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''HdnIdunico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdunico As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnIdDocumento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdDocumento As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdnIdTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdnIdTab As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''PnlCNCOb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlCNCOb As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tblGralCumpleNoCumple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblGralCumpleNoCumple As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''RbtnSiNoCumple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RbtnSiNoCumple As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TxtobservaCumpleNoCumple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtobservaCumpleNoCumple As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''trTipificaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTipificaciones As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ChkBltsTipifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkBltsTipifica As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''LblobservaCNC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblobservaCNC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnEnviarCNCGral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviarCNCGral As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCrearTarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCrearTarea As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnHabilitaCNCgral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHabilitaCNCgral As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ModalSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalSuspenderTitulo As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlSuspenderTitulo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblObservacionSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacionSuspenderTitulo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObservacionSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionSuspenderTitulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqObservacionSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqObservacionSuspenderTitulo As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmdSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSuspenderTitulo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCerrarSuspenderTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCerrarSuspenderTitulo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''modalVerDocMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalVerDocMD As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''PnlDocMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlDocMD As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hdnIdDocUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIdDocUpdate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblErrorDocUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorDocUpdate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDocUpdateEnviada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocUpdateEnviada As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarga As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlinkViewDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlinkViewDoc As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblNumPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPaginas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtNumPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPaginas As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqNumPaginas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqNumPaginas As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblObservacionLegibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblObservacionLegibilidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtObservacionLegibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionLegibilidad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''reqObservacionLegibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqObservacionLegibilidad As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''cmdAsignarDocumentoMetaData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAsignarDocumentoMetaData As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCloseVerDocMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseVerDocMD As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnActualizarMetaDataTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActualizarMetaDataTest As Global.System.Web.UI.WebControls.Button
End Class
