'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditEJEFISGLOBALREPARTIDOR
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''lblNomPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNomPerfil As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ABack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ABack As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''AShowExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AShowExp As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtEFINROEXP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFINROEXP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEFIFECHAEXP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIFECHAEXP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEFINUMMEMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFINUMMEMO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEFIEXPORIGEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIEXPORIGEN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEFIEXPDOCUMENTIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIEXPDOCUMENTIC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator1 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdGestionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGestionar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtEFIFECCAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIFECCAD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboRepartidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRepartidor As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtRevisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevisor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboEFIUSUASIG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEFIUSUASIG As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboEFIESTADO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEFIESTADO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboEFIESTADOPAGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEFIESTADOPAGO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEFIFECENTGES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEFIFECENTGES As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidator2 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''cmdMostrarEstadisticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMostrarEstadisticas As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdSave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdRefrescar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefrescar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cboTitEjecAntig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTitEjecAntig As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboCaducidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCaducidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboEstadoPersona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEstadoPersona As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboProcesoCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboProcesoCurso As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboAcuerdoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAcuerdoPago As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnObtenerEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnObtenerEstado As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtExtadoInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtadoInicial As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''grd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd As Global.System.Web.UI.WebControls.GridView
End Class
